"""Initial migration

Revision ID: 17cddb5b604b
Revises: 
Create Date: 2025-06-12 16:37:50.792173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cddb5b604b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golf_session',
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golf_session_session_id'), 'golf_session', ['session_id'], unique=True)
    op.create_index(op.f('ix_golf_session_user_id'), 'golf_session', ['user_id'], unique=False)
    op.create_table('golf_transcript',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('assistant_response', sa.Text(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=255), nullable=True),
    sa.Column('contains_wake_word', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['golf_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golf_transcript_session_id'), 'golf_transcript', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_golf_transcript_session_id'), table_name='golf_transcript')
    op.drop_table('golf_transcript')
    op.drop_index(op.f('ix_golf_session_user_id'), table_name='golf_session')
    op.drop_index(op.f('ix_golf_session_session_id'), table_name='golf_session')
    op.drop_table('golf_session')
    # ### end Alembic commands ###
